############################
## CHANGE THESE
############################

baseURL: 'https://Sergius81.github.io/sergius'
title: SERGIUS

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'de'
