############################
## Navbar
############################

main:
- name: Start
  url: /
  weight: 10
- name: Wiki
  url: https://wiki-sergius2-0138d818eaf5d398894ae69b386c731c8ab22c914753b158c.gitlab.io/
  weight: 20
- name: Über
  url: /about/
  weight: 30
- name: PYT
  url: https://pyt-academy.github.io/
