############################
## Author
############################

author:
  name: Sergius
  image: author.png
  greeting: "'Hallo Welt'"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/Sergius81
  - link: http://sergius.xyz
  # - website: http://sergius.xyz
  # - x-twitter:
  - mastodon: https://mastodon.social/@sergius_m
  # - linkedin:
  - instagram: https://instagram.com/sergius490
  # - reddit:
  - telegram: https://t.me/IT_Systemhaus
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - email:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  - patreon: https://patreon.com/user?u=67742872
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  - youtube: https://www.youtube.com/channel/UC3UmA3JI7pSZZ7v4O3wNiDA
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  - paypal: https://www.paypal.me/SergiusMuschalle
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: sergius
description: "Seite gebaut mit Qubt & Hugo"
images:
  - thumbnail.png
